name: Retrieve Branch Name
on:
  pull_request:
    branches: main
    types: [opened]

jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Branch Name
        run: echo "Current Branch:${{ github.head_ref }}"

