name: Manual host setup with the SNP latest upstream Kernel
on:
  workflow_dispatch:
    inputs:
      snp-kernel-host-guest-tag:
        description: 'Specify SNP kernel tag version(e.g: v6.10)'
jobs:
  snp_setup:
    runs-on: self-hosted
    timeout-minutes: 30 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Latest SNP Kernel on the self-hosted runner
        run: |
            echo "Installing SNP on the host..."
            
            # Cleanup 
            [ ! -f "~/snp.sh" ] || rm -rf ~/snp.sh
            [ ! -d "~/previous_snp" ] || rm -rf ~/previous_snp
            [ ! -d "~/snp" ] || mv ~/snp ~/previous_snp

            # Downloads sev utility script to setup host SNP kernel
            wget https://raw.githubusercontent.com/LakshmiSaiHarika/sev-utils/Fedora-Latest-SNP-kernel-Upstream/tools/snp.sh
            chmod +x snp.sh
            
            # # Sets up the user given latest upstream SNP host kernel/master branch 
            # kernel_host_guest_branch_tag="${{ github.event.inputs.snp-kernel-host-guest-tag }}"
            # if [[ ! -z "${kernel_host_guest_branch_tag}" ]]; then
            #   ./snp.sh --kernel-tag "${kernel_host_guest_branch_tag}" setup-host
            # else
            #   # Uses kernel upstream default master branch for kernel installation  
            #   ./snp.sh setup-host
            # fi     
            
  reboot_self_hosted_runner:
    runs-on: self-hosted
    steps:
      - name: Reboot
        timeout-minutes: 8
        run: sudo reboot
        shell: bash
        
  add_timer_between_jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Sleep for 5 minutes
        timeout-minutes: 5
        run: sleep 300s
        shell: bash

  trigger_pr_tests:
    runs-on: self-hosted
    timeout-minutes: 30 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger snpguest CI PR test on the self-hosted runner
        run: | 
            # Downloads sev utility script to setup host SNP kernel
            python /home/virtee/automation_scripts/trigger_pr_tests.py
