name: Manual host setup with the SNP latest upstream Kernel
on:
  workflow_dispatch:
    inputs:
      snp-kernel-host-guest-tag:
        description: 'Specify SNP kernel tag version(e.g: v6.10)'
  # Suggested Move: Run this workflow every night to update to SNP host kernel to latest
  # schedule:
  #  - cron: "0 0 * * *"

jobs:
  snp_setup:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Latest SNP Kernel on self-hosted runner
        run: |
            echo "Installing SNP on the host..."
            mv ~/snp ~/previous_snp_version_2
            rm -rf ~/snp.sh
            wget https://raw.githubusercontent.com/LakshmiSaiHarika/sev-utils/Fedora-Latest-SNP-kernel-Upstream/tools/snp.sh
            chmod +x snp.sh

            local kernel_host_guest_branch_tag= "${{ github.event.inputs.snp-kernel-host-guest-tag }}"
            if [[ ! -z "${kernel_host_guest_branch_tag}" ]]; then
              ./snp.sh --kernel-tag "${kernel_host_guest_branch_tag}" setup-host
            else
              # Uses kernel upstream default master branch for kernel installation  
              ./snp.sh setup-host
            fi
            
            echo "The host must be rebooted for changes to take effect."

      - name: Reboot self-hosted runner
        run: sudo reboot
